### ISSUE TITLE
Endless redirect loop on install

### ISSUE THREAD

**Issue by jakubsenk** [smartstore/Smartstore#1097]
**Describe the bug**
Hello, I deployed Smartstore on Windows server IIS hosting, but when I run it and try to access the web (through domain or even through localhost) it gets stuck in endless redirecting to install page.
However, when I build and run the web locally through visual studio the redirect works as expected.

**To Reproduce**
1. Deploy Smartstore to Windows hosting
2. Visit the website
4. See endless redirecting loop error

**Expected behavior**
It should display the install page.

**Screenshots**
![obrazek](https://github.com/smartstore/Smartstore/assets/29975881/0b4f555f-82aa-401d-adfe-fb2c1e74ad94)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Datacenter x64
 - Browser: not related

**Additional context**

**Comment by muratcakir** [comment]
Sounds like something that has been fixed in 3ac6b2c and in 2371a15

**Comment by jakubsenk** [comment]
These commits are 2 weeks old. I was using current development branch from this week. So I am afraid the problem still persists.

**Comment by muratcakir** [comment]
Not reproducible
