### ISSUE TITLE
Error while processing bundle '/themes/flex/theme.css'.

### ISSUE THREAD

**Issue by mchinchilla** [smartstore/Smartstore#457]
Hello all,
I just published the project and tried to run in Debian Linux 10 (Nginx as proxy). I got this error:

[02:33:48 ERR] Error while processing bundle '/themes/flex/theme.css'.
System.InvalidOperationException: The bundle '/themes/flex/theme.css' does not contain any files.
   at Smartstore.Web.Bundling.DefaultBundleBuilder.BuildBundleAsync(Bundle bundle, BundleCacheKey cacheKey, IDictionary`2 dataTokens, HttpContext httpContext, BundlingOptions options) in repos\Smartstore\src\Smartstore.Web.Common\Bundling\BundleBuilder.cs:line 80
   at Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in repos\Smartstore\src\Smartstore.Web.Common\Bundling\BundleMiddleware.cs:line 76
[02:33:48 ERR] HTTP GET /themes/flex/theme.css responded 500 in 1.6581 ms

I noticed the Path: /themes/flex/theme.css is in lower case and the Directory in File System is: /Themes/Flex/theme.css

Running the project in Visual Studio IDE everything is good, I'm missing something??

**Screenshots**
![image](https://user-images.githubusercontent.com/5103578/143408099-9cdbd18b-0617-4ab0-94f7-a11fa26fd68b.png)

![image](https://user-images.githubusercontent.com/5103578/143408440-47440f12-7baa-42af-a4d4-d35e201ba098.png)

Thank you in advance.

MCh.

**Comment by muratcakir** [comment]
> I noticed the Path: /themes/flex/theme.css is in lower case and the Directory in File System is: /Themes/Flex/

`/themes/flex/theme.css` is just a virtual path, the actual files are resolved by [ResolveThemeSourceFiles](https://github.com/smartstore/Smartstore/blob/2e49f3ed7d682ee0e3a70c623304283c4001533a/src/Smartstore.Web/Infrastructure/PublicBundles.cs#L13). But to be sure: could you please rename the folder name - `Flex` --> `flex` - and try again?

**Comment by mchinchilla** [comment]
I'll try it, but yesterday I tested making symbolic links:

![image](https://user-images.githubusercontent.com/5103578/143492881-35902917-443f-4d4f-bcf3-58eeba4b68c2.png)

 and

![image](https://user-images.githubusercontent.com/5103578/143492841-871b05f0-e691-4177-862f-f694e0c0da2c.png)

**Comment by mchinchilla** [comment]
Still the same.

Error: 
2021-11-25 13:45:55.148 -06:00 [ERR] Error while processing bundle '/themes/flex/theme.css'.
System.InvalidOperationException: The bundle '/themes/flex/theme.css' does not contain any files.
   at Smartstore.Web.Bundling.DefaultBundleBuilder.BuildBundleAsync(Bundle bundle, BundleCacheKey cacheKey, IDictionary`2 dataTokens, HttpContext httpContext, BundlingOptions options) in C:\Users\user\source\repos\Smartstore\src\Smartstore.Web.Common\Bundling\BundleBuilder.cs:line 80
   at Smartstore.Web.Bundling.BundleMiddleware.InvokeAsync(HttpContext httpContext) in C:\Users\user\source\repos\Smartstore\src\Smartstore.Web.Common\Bundling\BundleMiddleware.cs:line 76
2021-11-25 13:45:55.157 -06:00 [ERR] HTTP GET /themes/flex/theme.css responded 500 in 21.0261 ms

Here the log file ... (line 1376)

[log-20211125.log](https://github.com/smartstore/Smartstore/files/7605035/log-20211125.log)

**Comment by muratcakir** [comment]
You shouldn't  change `Themes` to `themes`. Please have a closer look at [ResolveThemeSourceFiles](https://github.com/smartstore/Smartstore/blob/2e49f3ed7d682ee0e3a70c623304283c4001533a/src/Smartstore.Web/Infrastructure/PublicBundles.cs#L16).
